### ISSUE TITLE
Pulling from gitlab leads to build failure

### ISSUE THREAD

**Issue by hanscol** [dchristiaens/shard-recon#1]
Currently the README has the user pull from the gitlab page, but I found that this will result in a build error even with mrtrix3 and eigen 3.3.3 installed. Pulling from the github led to a successful  build.

**Comment by dchristiaens** [comment]
Hi Colin,

You are absolutely right. Thanks for pointing this out, the `README.md` file has now been updated.

Cheers
Daan
