### ISSUE TITLE
Installing with MRtrix3 Anaconda Environment

### ISSUE THREAD

**Issue by smeisler** [dchristiaens/shard-recon#15]
Hi,

Due to being on a HPC without root permission, I cannot compile MRtrix3. Instead I use containerized versions and also have a MRtrix3 anaconda environment. Do you have any suggestions as to how I could install this module without being able to build from source?

Thanks,
Steven

**Comment by dchristiaens** [comment]
Hi Steven - Sorry, currently you need to build the module from source. However, you don't need root permissions to compile MRtrix and its modules. You can clone the repositories in your home directory and run the `configure` and `build` scripts with normal user rights. You do need to have the [dependencies](https://mrtrix.readthedocs.io/en/latest/installation/build_from_source.html#install-dependencies) installed, but you can use those of your Anaconda setup.
