### ISSUE TITLE
dwimotioncorrect: [ERROR] -rlmax invalid.

### ISSUE THREAD

**Issue by hitrp** [dchristiaens/shard-recon#18]
Dear Prof.Christiaens

I found an error like this when running dwimotioncorrect, could you give some suggestions?

dwimotioncorrect den_unring_preproc.mif den_unring_preproc_a.mif -force 
dwimotioncorrect: [ERROR] -rlmax invalid.

Best wishes,
Peng

**Comment by dchristiaens** [comment]
Hi Peng,

Is it possible you're using single-shell data? The default setting for `-rlmax` is `2,2,0`, which is not compatible with single-shell data. If you override the default, e.g., with `-rlmax 2,0` the command should run.

There are 2 options related to the basis rank used in the process: 

- `-lmax` is the degree of the SH basis per shell used for _reconstruction_, i.e., for fitting the signal representation of the motion-corrected subject to the scattered slice data. The default is 0 for b=0 and 4 for all b>0 shells. It is usually advisable to increase its value depending on the number of samples per shell.
- `-rlmax` defines the rank of the _reduced_ SHARD basis used for _registration_, i.e., for determining the motion parameters of each slice in the subject reference frame. This needs to be smaller than the full multi-shell SH basis rank to ensure robust alignment and is provided as a list of the SH degree of each successive component, sorted in decreasing order.

For instance, in a 3-shell dataset with [10, 25, 40, 60] samples at b=[0, 1000, 2000, 3000] s/mm^2, you could set `-lmax 0,4,6,8` and `-rlmax 4,2,0`.

I appreciate that this may be a bit confusing. I'll look into defining a more sensible default that is compatible with single-shell data.

Hope this helps,

Daan

**Comment by hitrp** [comment]
Dear Prof. Christiaens,

You are right, it works after changing the -rlmax to 2,0,  as shown in the figure, the output of the command still contains some signal dropout, I didn't find anything about multi-band, so I guess the multi-band factor should be 1, as for the -sorder option, I think the following slice order matches that of the default odd-even order. Are there any suggestions for the further correction of our single b0 image?

Here are the scanning parameters:
Cardiac-triggered DTI MR sequences were acquired on a Siemens 3T TIM Trio scanner using a 12-channel matrix head coil and a two-dimensional echo-planar DTI sequence with the following parameters: TR/TE = 900/88 ms, flip angle = 90°, voxel size = 2 × 2 × 2 mm, 72 slices, **64 gradient directions with a b-value of 1000 s/mm2. One non-gradient volume (b = 0 s/mm2) was also acquired.** 

slice order:
 0
 11
 22
 33
 44
 55
 66
  1
 12
 23
 34
 45
 56
 67

After motionCorrection;         Before motionCorrection
![image](https://user-images.githubusercontent.com/30931150/162734997-7f34e7e0-88fd-496b-9098-8c999732634c.png)


Best wishes,
Peng

**Comment by dchristiaens** [comment]
Dear Peng,

TR = 900ms is very short. Based on the image you shared, it looks like this may be causing a spin history artefact in you data? The pattern looks too regular to be a motion-induced slice dropout. Either way, with a single b=0 image the scope for good dropout correction is limited.

The slice order is also very unusual. If this is indeed how the data was acquired, you need to set `-sorder 11,1`.

Based on the number of volumes and the b-value, I think these settings should be reasonable:
```
dwimotioncorrect den_unring_preproc.mif -mask reconmask.mif -lmax 0,6 -rlmax 2,0 -sorder 11,1 den_unring_preproc_mssh.mif
mssh2amp den_unring_preproc_mssh.mif grad.b den_unring_preproc_dwi.mif
```
Not how I also included a (rough) reconstruction mask. You can get this with `dwi2mask` on the input data. The gradient scheme `grad.b` can also be taken from the input data.

Cheers
Daan

**Comment by hitrp** [comment]
Dear Daan,

Sorry for the delay, I found that the SHARD with the new parameter didn't improve much on the result.
After motionCorrection; Before motionCorrection
![image](https://user-images.githubusercontent.com/30931150/163588180-2ae53c11-360c-43fa-8cc0-61f0612b0ef1.png)

Are there any other suggestions or Is this the shortage of the single b0 image?

Best wishes,
Peng

**Comment by dchristiaens** [comment]
> Are there any other suggestions or Is this the shortage of the single b0 image?

The single b=0 image doesn't help, but more fundamentally it looks like there is a strong striping artefact in your input data that is not related to motion.

---
I'm closing this issue since the reported bug with single-shell data has been fixed.
