### ISSUE TITLE
mssh2amp: `0 0 0` directions yield NaNs

### ISSUE THREAD

**Issue by maxpietsch** [dchristiaens/shard-recon#6]
all zero gradients (direction and b-value:`0 0 0 0`) in the gradient table file causes all NaN values in the output DWI, maybe linked to https://github.com/MRtrix3/mrtrix3/issues/2231?

**Comment by dchristiaens** [comment]
Fixed in https://github.com/MRtrix3/mrtrix3/issues/2231 and with commit 9bf9ba2752b40df6be1470aed3669fa48336ab0f.
